services:
  app:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.5.0
    ports:
      - '9090:9090'
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.0.2
    ports:
      - '3001:3000'
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: 'false'
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
    restart: unless-stopped
